### ISSUE TITLE
The links are prefixed with http instead of https

### ISSUE THREAD

**Issue by saberraz** [lutraconsulting/mergin-media-sync#6]
We should check if the back-end storage supports https and if so, prefix the paths in the fields with https. Currently, http is used everywhere.

**Comment by wonder-sk** [comment]
@varmar05 isn't the HTTPS option broken because in the code https://github.com/lutraconsulting/mergin-media-sync/blob/main/drivers.py#L73 we check for `config.as_bool("secure")` instead of `config.as_bool("minio.secure")` ?

**Comment by varmar05** [comment]
@wonder-sk yes, it seems that way
